-- create
CREATE TABLE EMPLOYEE (
  id INTEGER PRIMARY KEY,
  name TEXT NOT NULL,
  age TEXT NOT NULL
);

-- insert
INSERT INTO EMPLOYEE VALUES (0001, 'Иван', '18');
INSERT INTO EMPLOYEE VALUES (0002, 'Петр', '22');
INSERT INTO EMPLOYEE VALUES (0003, 'Анна', '35');
INSERT INTO EMPLOYEE VALUES (0004, 'Юлия', '18');
INSERT INTO EMPLOYEE VALUES (0005, 'Николай', '36');

-- fetch 
SELECT * FROM EMPLOYEE WHERE age > '18';